---
- name: setup a repoisitory server
  hosts: localhost

  tasks:

  - name: install vsftpd
    yum:
      name: vsftpd
      state: present

  - name: enable vsftpd service
    service:
      name: vsftpd
      state: started
      enabled: true

  - name: config selinux boolean for ftp access
    seboolean:
      name: ftpd_full_access
      state: yes
      persistent: yes

  - name: disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false

  - name: create public ftp dir
    file:
      path: /var/ftp/repo
      state: directory

  - name: mount repo dir
    mount:
      src: /dev/sr0
      path: /var/ftp/repo
      fstype: iso9660
      opts: defaults
      state: mounted

  - name: config vsftpd.conf
    lineinfile:
      path: /etc/vsftpd/vsftpd.conf
      regexp: '^anonymous_enable.+$'
      line: 'anonymous_enable=YES'
      state: present
    changed_when: true
    notify: restart vsftpd

  handlers:

  - name: restart vsftpd
    service:
      name: vsftpd
      state: restarted
