---
- name: configure /etc/hosts file
  hosts: all
  tasks:

  - name: copy template to /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
      backup: true
      owner: root
      group: root
      mode: 0640
