---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: awx-postgres
  port: "5432"
  database: awx
  username: awx
  password: <awxdatabaseadmin>    # Set the database password you wish to use.
  type: managed
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: awx
stringData:
  password: <awxadmin>    # Set the default Admin password for awx.
type: Opaque
