---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: awx-postgres
  port: "5432"
  database: awx
  username: awx
  password: <awxdatabaseadmin>    # Set the database password you wish to use.
  type: managed
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: awx
stringData:
  password: <awxadmin>    # Set the default Admin password for awx.
type: Opaque

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:

  admin_user: admin
  admin_password_secret: awx-admin-password

  service_type: nodeport
  ingress_type: none
  hostname: awx.example.com     # Replace fqdn.awx.host.com with Host FQDN and DO NOT use IP.
