---
- name: create partition and volume group on managed hosts
  hosts: ansible1.example.com,ansible3.example.com

  vars:
    partitions:
      - host: ansible1
        part_end: 1GiB
      - host: ansible3
        part_end: 3GiB
    vgname: vgdata

  tasks:

  - name: create partition
    parted:
      device: /dev/sdb
      number: 1
      part_end: "{{ item.part_end }}"
      flags: [ lvm ]
      state: present
    loop: "{{ partitions }}"
    when: ansible_hostname == item.host

  - name: create volume group
    lvg:
      vg: "{{ vgname }}"
      pvs: /dev/sdb1
